- hosts: 'workers, masters'
  become: yes

  tasks:
    - name: allow 'touadmin' to use sudo without needing a password
      lineinfile:
        dest: /etc/sudoers
        line: 'touadmin ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the kube user
      authorized_key: user=kube key= "{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub
