---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Clone VM from template
      community.vmware.vmware_guest:
        hostname: "192.168.61.150"
        username: "harithasri.pentam@tou.toucanus.ads.net"
        password: "Welcome@123"
        validate_certs: no
        name: "{{ vm_name }}"
        template: "Test-gold image"
        datacenter: "Datacenter-Hyderabad"  # Replace with actual name
        esxi_hostname: "192.168.63.24"
        folder: "/vm"
        state: poweredon
        hardware:
          memory_mb: "{{ memory_gb | int * 1024 }}"
          num_cpus: "{{ cpu }}"
        networks:
          - name: "VM Network"
            ip: "{{ ip_address }}"
            netmask: "255.255.248.0"
            gateway: "192.168.63.250"
            dns_servers:
              - "8.8.8.8"
              - "8.8.4.4"
        disk:
          - size_gb: "{{ disk_size_gb }}"
            type: thin
            datastore: "VMs"
      delegate_to: localhost

